- id: '1652881309414'
  alias: vvtank_on update
  description: ''
  trigger:
  - platform: template
    value_template: "{{ states.binary_sensor.vvtank_on.state == 'on' \nand states.switch.vv_tank.state\
      \ == 'off'\nand now().timestamp() - states.switch.vv_tank.last_updated.timestamp()\
      \ > 30 }}"
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: vvtank_on ser ut til å henge
      title: 'vvtank debug '
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.vv_tank_electric_consumption_w
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - condition: template
    value_template: '{{ states.switch.vv_tank.state == ''off'' and states.binary_sensor.vvtank_on.state
      == ''on'' }}'
  - service: notify.persistent_notification
    data:
      message: vvtank_on ser fortsatt ut til å henge litt
      title: 'vvtank debug '
  mode: single
- id: '1652905890675'
  alias: Styr lys i gangen
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.shellygang_input
  - platform: state
    entity_id: sensor.howmanyhome
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.shellygang_input
        state: 'off'
      sequence:
      - service: light.turn_on
        data:
          brightness: 4
        target:
          entity_id: light.lys_i_gangen
    - conditions:
      - condition: template
        value_template: '{{ states.sensor.howmanyhome.state|int == 0 }}'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.lys_i_gangen
        data: {}
    default:
    - service: light.turn_on
      data:
        brightness: 204
      target:
        entity_id: light.lys_i_gangen
  mode: single
- id: '1653390572240'
  alias: Kjøkken på svakt på kvelden
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bevegelse_kjokken_occupancy
  condition:
  - condition: device
    type: is_on
    device_id: 2b2fb3d0e3b9d5a4815a9120de84afbb
    entity_id: light.livingroom_lights
    domain: light
  action:
  - choose:
    - conditions:
      - type: is_motion
        condition: device
        device_id: 31f5236faab8ab70132e1e5bb341a5d8
        entity_id: binary_sensor.bevegelse_kjokken_occupancy
        domain: binary_sensor
      sequence:
      - type: turn_on
        device_id: 2336ec55a36729c3797ce9e76358ed13
        entity_id: light.kitchen_lights
        domain: light
        brightness_pct: 95
    default:
    - type: turn_on
      device_id: 2336ec55a36729c3797ce9e76358ed13
      entity_id: light.kitchen_lights
      domain: light
      brightness_pct: 30
  mode: single
- id: '1654601572540'
  alias: Lys på i hagestue
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.pvlogger_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: '100'
    id: low light
  - platform: time
    at: 01:30:00
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: low light
      - condition: time
        after: '12:00:00'
        before: '23:59:00'
      sequence:
      - type: turn_on
        device_id: d4305c6feca526b0e16cdecff1d937d6
        entity_id: light.hagestue
        domain: light
    - conditions:
      - condition: device
        type: is_on
        device_id: d4305c6feca526b0e16cdecff1d937d6
        entity_id: light.hagestue
        domain: light
      sequence:
      - type: turn_off
        device_id: d4305c6feca526b0e16cdecff1d937d6
        entity_id: light.hagestue
        domain: light
    default: []
  mode: single
