sensor:
  - name: wind_direction
    state: >
      {% set grades = states('sensor.ws2900_v2_02_02_wind_direction')|float %}
      {{ 'N' if grades > 337.5 or grades < 22.5 else
         'NE' if grades < 67.5 else
         'E' if grades < 112.5 else
         'SE' if grades < 157.5 else
         'S' if grades < 202.5 else
         'SW' if grades < 247.5 else
         'W' if grades < 292.5 else
         'NW' }}
  - name: windspeed_ms
    state: '{{ (states(''sensor.ws2900_v2_02_02_wind_speed'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: windgust_ms
    state: '{{ (states(''sensor.ws2900_v2_02_02_wind_gust'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: howmanyhome
    unit_of_measurement: 'stk'
    state: "{{ states.person | selectattr('state','eq','home') | list | count }}"
  - name: outside_temp
    unit_of_measurement: '°C'
    state: >
      {% set o = namespace (temp=[]) %} 
      {% if not states('sensor.ws2900_v2_02_02_outdoor_temperature') in ['unavailable', 'unknown'] %}
        {% set o.temp = o.temp + [ states('sensor.ws2900_v2_02_02_outdoor_temperature')|float ] %}
      {% endif %}
      {% if not states('sensor.lumi_ute_temperature') in ['unavailable', 'unknown'] %}
        {% set o.temp = o.temp + [ states('sensor.lumi_ute_temperature')|float ] %}
      {% endif %}
      {{ o.temp|average|round(1) if o.temp|length > 0 else 'undefined' }}
      

binary_sensor:
  - name: winter_tires_check
    state: '{{ states.input_boolean.winter_tyres.state == states.binary_sensor.tires_for_rypeveien.state }}'
  - name: vaskemaskin_on
    state: '{{ states(''sensor.stikk_vaskemaskin_power'')|float(default=0) > 2 }}'
    delay_off: 
      minutes: 2
  - name: kjolerom_on
    state: "{{ states('sensor.shellykjol_switch_0_power')|float(default=0) > 20 }}"
  - name: torketrommel_on
    state: "{{ states('sensor.stikk_torketrommel_power')|float(default=0) > 20 }}"
    delay_on: 
      minutes: 2
    delay_off: 
      minutes: 2
  - name: zwift_online
    state: "{{ states('sensor.zwift_online_1180851') == 'True' }}"
  - name: anyone_home
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
  - name: dor_inngang_on
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_off: 
      minutes: 5
  - name: dor_inngang_open
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_on:
      minutes: 2
    delay_off:
      minutes: 5
  - name: verandador_open
    state: '{{ states(''binary_sensor.verandador_contact'') == ''on'' }}'
    delay_on:
      minutes: 2
    delay_off: 
      minutes: 5
  - name: soverom_unavailable
    state: "{{ is_state('sensor.soverom_temperature', 'unavailable') }}"
