sensor:
  - name: energy_subsides
    unit_of_measurement: 'NOK/kWh'
    state: >
      {% set raw = states('input_number.energy_raw_month_average')|float %}
      {{ (raw - 0.7)|round(4) if raw > 0.7 else 0 }}
  - name: windspeed_ms
    state: '{{ (states(''sensor.netatmo_rypeveien_netatmo_vindmaler_wind_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: windgust_ms
    state: '{{ (states(''sensor.netatmo_rypeveien_netatmo_vindmaler_gust_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: fa_adax_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_faoff','current_temperature') }}"
  - name: syrom_adax_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_syrom','current_temperature') }}"
  - name: gjesterom_adax_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_guest','current_temperature') }}"
  - name: fa_adax_power
    unit_of_measurement: "W"
    device_class: power
    state: >
      {% set s = 'adax_faoff' %}
      {% set d = state_attr ('climate.' + s, 'temperature') - state_attr ('climate.' + s, 'current_temperature') %}
      {% if d > 3.5 %}
        600
      {% elif d > 0.5 %}
        300
      {% else %}
        0
      {% endif %}
  - name: adax_guest_power
    unit_of_measurement: "W"
    device_class: power
    state: >
      {% set s = 'adax_guest' %}
      {% set d = state_attr ('climate.' + s, 'temperature') - state_attr ('climate.' + s, 'current_temperature') %}
      {% if d > 3.5 %} 600 {% elif d > 0.5 %} 300 {% else %} 0 {% endif %}
  - name: adax_syrom_power
    unit_of_measurement: "W"
    device_class: power
    state: >
      {% set s = 'adax_syrom' %}
      {% set d = state_attr ('climate.' + s, 'temperature') - state_attr ('climate.' + s, 'current_temperature') %}
      {% if d > 3.5 %} 600 {% elif d > 0.5 %} 300 {% else %} 0 {% endif %}
  - name: cheap_x_kwh_hours
    state: >
      {% set today = states('sensor.energy_today_nok_kwh')|from_json %}
      {% set tomorrow = states('sensor.energy_tomorrow_nok_kwh')|from_json %}
      {% set prices = today[now().hour:24] %}
      {% if tomorrow|length > 0 %}
      {% set prices = prices + tomorrow %}
      {% endif %}
      {% set prices = prices[0:24] %}
      {% set all = namespace(done = False) %}
      {% set hours = namespace(to = '') %}
      {% set max = prices | length %}
      {% if max > 12 %}
        {% set max = 12 %}
      {% endif %}
      {% for j in range(max) %}
        {% set all.done = False if j < max else True %}
        {% set sums = namespace(sums = []) %}
        {% for i in range(prices|length - j) %}
          {% set sums.sums = sums.sums + [prices[i:i+j+1]|sum] %}
        {% endfor %}
        {% set sums.sums = sums.sums[:max] %}
        {% set lowsum = (sums.sums| sort)[0] %}
        {% for i in range (sums.sums|count) %}
          {% if (sums.sums[i] <= lowsum ) %}
            {% if hours.to == '' %}
              {% set hours.to = i|string %}
            {% else %}
              {% set hours.to = hours.to + ', ' + i|string %}
            {% endif %}
          {% endif %}    
        {% endfor %}
      {% endfor %}
      {{ hours.to }}
  - name: howmanyhome
    unit_of_measurement: 'stk'
    state: "{{ states.person | selectattr('state','eq','home') | list | count }}"

binary_sensor:
  - name: winter_tires_check
    state: '{{ states.input_boolean.winter_tyres.state == states.binary_sensor.snowtire.state }}'
  - name: laptoplader_on
    state: '{{ states(''sensor.laptoplader_electric_consumption_w'')|float(default=0) > 5 }}'
  - name: vvtank_on
    state: '{{ states(''sensor.vv_tank_electric_consumption_w'')|float(default=0) > 0 }}'
  - name: vvkjeller_on
    state: '{{ states(''sensor.vv_kjeller_power'')|float(default=0) > 0 }}'
  - name: vaskemaskin_on
    state: '{{ states(''sensor.shellyvask_power'')|float(default=0) > 2 }}'
    delay_off: 
      minutes: 2
  - name: kjolerom_on
    state: "{{ states('sensor.shellykjol_switch_0_power')|float(default=0) > 20 }}"
  - name: torketrommel_on
    state: "{{ states('sensor.torketrommel_power')|float(default=0) > 20 }}"
    delay_on: 
      minutes: 2
    delay_off: 
      minutes: 2
  - name: zwift_online
    state: "{{ states('sensor.zwift_online_1180851') == 'True' }}"
  - name: anyone_home
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
  - name: motion_inngang_on
    state: '{{ states(''binary_sensor.cam01_inngang'') == ''on'' }}'
    delay_off: 
      minutes: 5
  - name: dor_inngang_on
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_off: 
      minutes: 5
  - name: prices_nok_kwh_lowthird
    state: >
      {% set prices = states('sensor.energy_today_nok_kwh')|from_json %}
      {% set prices = prices[now().hour:] %}
      {% set tomorrow =  states('sensor.energy_tomorrow_nok_kwh')|from_json %}
      {% if tomorrow|length > 0 %}
        {% set prices = prices + tomorrow %}
      {% endif %}
      {% set count=(prices|length/3)|int %}
      {{ prices[0] < (prices|sort)[count] }}
