sensor:
  - name: windspeed_ms
    state: '{{ (states(''sensor.netatmo_rypeveien_netatmo_vindmaler_wind_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: windgust_ms
    state: '{{ (states(''sensor.netatmo_rypeveien_netatmo_vindmaler_gust_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: howmanyhome
    unit_of_measurement: 'stk'
    state: "{{ states.person | selectattr('state','eq','home') | list | count }}"

binary_sensor:
  - name: winter_tires_check
    state: '{{ states.input_boolean.winter_tyres.state == states.binary_sensor.snowtire.state }}'
  - name: vvtank_on
    state: '{{ states(''sensor.vv_tank_electric_consumption_w'')|float(default=0) > 0 }}'
  - name: vvkjeller_on
    state: '{{ states(''sensor.vv_kjeller_power'')|float(default=0) > 0 }}'
  - name: vaskemaskin_on
    state: '{{ states(''sensor.stikk_vaskemaskin_power'')|float(default=0) > 2 }}'
    delay_off: 
      minutes: 2
  - name: kjolerom_on
    state: "{{ states('sensor.shellykjol_switch_0_power')|float(default=0) > 20 }}"
  - name: torketrommel_on
    state: "{{ states('sensor.stikk_torketrommel_power')|float(default=0) > 20 }}"
    delay_on: 
      minutes: 2
    delay_off: 
      minutes: 2
  - name: zwift_online
    state: "{{ states('sensor.zwift_online_1180851') == 'True' }}"
  - name: anyone_home
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
  - name: motion_inngang_on
    state: '{{ states(''binary_sensor.cam01_inngang'') == ''on'' }}'
    delay_off: 
      minutes: 5
  - name: dor_inngang_on
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_off: 
      minutes: 5
