sensor:
  - name: windspeed_ms
    state: '{{ (states(''sensor.netatmo_vindmaler_wind_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: windgust_ms
    state: '{{ (states(''sensor.netatmo_vindmaler_gust_strength'')|float / 3.6)|round(1) }}'
    unit_of_measurement: 'm/s'
  - name: howmanyhome
    unit_of_measurement: 'stk'
    state: "{{ states.person | selectattr('state','eq','home') | list | count }}"
  - name: outside_temp
    unit_of_measurement: '°C'
    state: >
      {% set o = namespace (temp=[]) %} 
      {% if not states('sensor.netatmo_ute_temperature') in ['unavailable', 'unknown'] %}
        {% set o.temp = o.temp + [ states('sensor.netatmo_ute_temperature')|float ] %}
      {% endif %}
      {% if not states('sensor.lumi_ute_temperature') in ['unavailable', 'unknown'] %}
        {% set o.temp = o.temp + [ states('sensor.lumi_ute_temperature')|float ] %}
      {% endif %}
      {{ o.temp|average|round(1) if o.temp|length > 0 else 'undefined' }}
      

binary_sensor:
  - name: winter_tires_check
    state: '{{ states.input_boolean.winter_tyres.state == states.binary_sensor.snowtire.state }}'
  - name: vaskemaskin_on
    state: '{{ states(''sensor.stikk_vaskemaskin_power'')|float(default=0) > 2 }}'
    delay_off: 
      minutes: 2
  - name: kjolerom_on
    state: "{{ states('sensor.shellykjol_switch_0_power')|float(default=0) > 20 }}"
  - name: torketrommel_on
    state: "{{ states('sensor.stikk_torketrommel_power')|float(default=0) > 20 }}"
    delay_on: 
      minutes: 2
    delay_off: 
      minutes: 2
  - name: zwift_online
    state: "{{ states('sensor.zwift_online_1180851') == 'True' }}"
  - name: anyone_home
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
  - name: dor_inngang_on
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_off: 
      minutes: 5
  - name: dor_inngang_open
    state: '{{ states(''binary_sensor.inngangsdor_door_window'') == ''on'' }}'
    delay_on:
      minutes: 2
    delay_on:
      minutes: 5
  - name: verandador_open
    state: '{{ states(''binary_sensor.verandador_contact'') == ''on'' }}'
    delay_on:
      minutes: 2
    delay_off: 
      minutes: 5
