template:
  sensor:
    - name: evnotify_12v
      unit_of_measurement: "V"
      state: "{{ state_attr('sensor.evnotify_ext', 'aux_battery_voltage') }}"

sensor:
  - platform: rest
    scan_interval: 300
#  evnotify_ext: "https://app.evnotify.de/extended?akey=myakey&token=mytoken"
    resource: !secret evnotify_ext
    name: "evNotify ext"
    value_template: '{{ value_json.dc_battery_power }}'
    unit_of_measurement: "kW"
    json_attributes:
      - "charging"
      - "aux_battery_voltage"
      - "last_extended"
      - "cumulative_energy_charged"
  - platform: rest
    scan_interval: 300
#  evnotify_soc: "https://app.evnotify.de/soc?akey=myakey&token=mytoken"
    resource: !secret evnotify_soc
    name: "evNotify soc"
    value_template: '{{ value_json.soc_display }}'
    unit_of_measurement: "%"
    json_attributes:
      - "soc_bms"
      - "last_soc"
  - platform: rest
    scan_interval: 300
#  evnotify_loc: "https://app.evnotify.de/location?akey=mykey&token=mytoken"
    resource: !secret evnotify_loc
    name: "evNotify loc"
    value_template: '{{ distance(value_json.latitude, value_json.longitude)|round(3) }} '
    unit_of_measurement: "km"
    json_attributes:
      - "latitude"
      - "longitude"
      - "gps_speed"
      - "last_location"
