input_boolean:
  homeoffice_monday:
    name: homeoffice_monday
  homeoffice_tuesday:
    name: homeoffice_tuesday
  homeoffice_wednesday:
    name: homeoffice_wednesday
  homeoffice_thursday:
    name: homeoffice_thursday
  homeoffice_friday:
    name: homeoffice_friday
  homeoffice_weekend:
    name: homeoffice_weekend

template: 
  sensor:
  - name: adax_faoff_analyze_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_faoff','current_temperature')|float - states('sensor.analyzer_updown')|int }}"
  - name: adax_syrom_analyze_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_syrom','current_temperature')|float - states('sensor.analyzer_updown')|int }}"
  - name: adax_guest_analyze_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_guest','current_temperature')|float - states('sensor.analyzer_updown')|int }}"
  - name: adax_faoff_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_faoff','current_temperature') }}"
  - name: adax_syrom_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_syrom','current_temperature') }}"
  - name: adax_guest_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.adax_guest','current_temperature') }}"
  - name: adax_faoff_power
    unit_of_measurement: "W"
    state: "{{ 600 if state_attr('climate.adaxg_faoff', 'hvac_action') == 'heating' else 0 }}"
  - name: adax_syrom_power
    unit_of_measurement: "W"
    state: "{{ 600 if state_attr('climate.adaxg_syrom', 'hvac_action') == 'heating' else 0 }}"
  - name: adax_guest_power
    unit_of_measurement: "W"
    state: "{{ 600 if state_attr('climate.adaxg_guest', 'hvac_action') == 'heating' else 0 }}"

  binary_sensor:
    - name: office_at_home
      state: > 
        {% set weekday = now().isoweekday () %}
        {{ (7 <= now().hour < 16) and (
           (states('input_boolean.homeoffice_monday') == 'on' and weekday == 1) or
           (states('input_boolean.homeoffice_tuesday') == 'on' and weekday == 2) or 
           (states('input_boolean.homeoffice_wednesday') == 'on' and weekday == 3) or 
           (states('input_boolean.homeoffice_thursday') == 'on' and weekday == 4) or
           (states('input_boolean.homeoffice_friday') == 'on' and weekday == 5) or
           (states('input_boolean.homeoffice_weekend') == 'on' and (weekday < 1 or weekday > 5)))
        }}

sensor:
- platform: integration
  source: sensor.adax_faoff_power
  name: adax_faoff_energy
  unit_prefix: k
  round: 3
  method: left
- platform: integration
  source: sensor.adax_syrom_power
  name: adax_syrom_energy
  unit_prefix: k
  round: 3
  method: left
- platform: integration
  source: sensor.adax_guest_power
  name: adax_guest_energy
  unit_prefix: k
  round: 3
  method: left

switch:
  - platform: template
    switches:
      adax_faoff:
        turn_on:
        turn_off:
      adax_syrom:
        turn_on:
        turn_off:
      adax_guest:
        turn_on:
        turn_off:

climate:
  - platform: generic_thermostat
    name: adaxg_faoff
    heater: switch.adax_faoff
    target_sensor: sensor.adax_faoff_analyze_temp
    target_temp_step: 1
  - platform: generic_thermostat
    name: adaxg_syrom
    heater: switch.adax_syrom
    target_sensor: sensor.adax_syrom_analyze_temp
    target_temp_step: 1
  - platform: generic_thermostat
    name: adaxg_guest
    heater: switch.adax_guest
    target_sensor: sensor.adax_guest_analyze_temp
    target_temp_step: 1
        
automation:
  - id: '1644843799898'
    alias: Adax varmestyring
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.office_at_home
      id: hjemmekontorvalg
    - platform: time
      at: 07:00
      id: morgen
    - platform: time
      at: '16:00'
      id: ettermiddag
    - platform: template
      value_template: '{{ now().timestamp() - as_timestamp(states.climate.adax_faoff.last_updated) > (3 * 3600) }}'
      id: lost_connection
    condition: 
    - condition: template
      value_template: '{{ states.automation.kontortemp.attributes.current == 0 }}'
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.office_at_home
          state: 'on'
        - condition: time
          after: 05:00
          before: '16:00'
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        - condition: numeric_state
          entity_id: climate.adaxg_faoff
          attribute: temperature
          below: '21'
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 21
          target:
            entity_id: climate.adaxg_faoff
      - conditions:
        - condition: numeric_state
          entity_id: climate.adaxg_faoff
          attribute: temperature
          above: '18.9'
        - condition: or
          conditions:
          - condition: state
            entity_id: binary_sensor.office_at_home
            state: 'off'
          - condition: not
            conditions:
            - condition: time
              after: 05:00
              before: '16:00'
              weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 14
          target:
            entity_id: climate.adaxg_faoff
      default: []
    - service: climate.set_temperature
      data: 
        temperature: "{{ state_attr('climate.adaxg_faoff', 'temperature')|float + 
                         states('sensor.analyzer_updown')|int }}"
      target:
        entity_id: climate.adax_faoff
    mode: queued
    max: 3

  - id: '1669366403330'
    alias: adjust adax temp according to generic thermostat, hvac action and analyzer_updown
    trigger:
      - platform: state
        entity_id: 
          - climate.adaxg_faoff
          - climate.adaxg_guest
          - climate.adaxg_syrom
        attribute: temperature
      - platform: state
        entity_id: 
          - climate.adaxg_faoff
          - climate.adaxg_guest
          - climate.adaxg_syrom
        attribute: hvac_action
      - platform: state
        entity_id:
          - sensor.analyzer_updown
    action:
      - delay: 
          seconds: 5
      - service: climate.set_temperature
        data: 
          temperature: >
            {% set action = 4 if state_attr('climate.adaxg_faoff', 'hvac_action') in ['heating'] else -1 %}
            {{ state_attr('climate.adaxg_faoff', 'temperature') + action + states('sensor.analyzer_updown')|int }}
        target:
          entity_id: climate.adax_faoff
      - service: climate.set_temperature
        data: 
          temperature: >
            {% set action = 4 if state_attr('climate.adaxg_guest', 'hvac_action') in ['heating'] else -1 %}
            {{ state_attr('climate.adaxg_guest', 'temperature') + action + states('sensor.analyzer_updown')|int }}
        target:
          entity_id: climate.adax_guest
      - service: climate.set_temperature
        data: 
          temperature: >
            {% set action = 4 if state_attr('climate.adaxg_syrom', 'hvac_action') in ['heating'] else -1 %}
            {{ state_attr('climate.adaxg_syrom', 'temperature') + action + states('sensor.analyzer_updown')|int }}
        target:
          entity_id: climate.adax_syrom
