switch: 
  - platform: template
    switches:
      bathroom_generic:
        value_template: "{{states('sensor.baderomsgulv_electric_consumption_w')|int > 50 }}"
        turn_on:
        turn_off:

climate:
  - platform: generic_thermostat
    name: bathroom_temp
    heater: switch.bathroom_onoff
    target_sensor: sensor.bathroom_temp
    target_temp_step: 0.5
    min_temp: 14
    max_temp: 28
  - platform: generic_thermostat
    name: aux_bathroom_heat
    heater: switch.shellyhybelbadvarme
    target_sensor: sensor.lumi_bad_nede_temperature
    target_temp_step: 1
    min_temp: 14
    max_temp: 28

template:
  sensor:
  - name: bathroom_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.baderomsgulv', 'current_temperature') - states('sensor.analyzer_updown')|int * 0.5 }}"
  - name: bathroom_target
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.bathroom_temp', 'temperature') + 0.5 * states('sensor.analyzer_updown')|int(default=0) }}"

automation:
  - id: '1662913867828'
    alias: Bathroom Analyzer temp adjustment
    trigger: 
      - platform: state
        entity_id: sensor.bathroom_target
    action: 
    - service: climate.set_temperature
      data: 
        temperature: sensor.bathroom_target
      target:
        entity_id: climate.baderomsgulv

  - id: '20250110105100'
    alias: Bathroom local adjustment
    trigger: 
      - device_id: e0ac5b2793a023a80c152ccf6bbba94d
        domain: zwave_js
        type: zwave_js.value_updated.value
        trigger: device
        property: setpoint
        command_class: 67
        property_key: "1"
        endpoint: "1"
    action: 
    - service: climate.set_temperature
      data: 
        temperature: >
            {{ state_attr('climate.baderomsgulv', 'temperature') - 0.5 * states('sensor.analyzer_updown')|int(default=0) }}
      target:
        entity_id: climate.bathroom_temp

