input_number:
  bathroom_temp: 
    name: Bathroom target temp 
    max: 27
    min: 10
    step: 0.5
    mode: slider

automation:
  - id: '1662913867828'
    alias: Bathroom Analyzer temp adjustment
    trigger: 
      - platform: state
        entity_id: sensor.analyzer_updown
      - platform: state
        entity_id: input_number.bathroom_temp
    condition: 
    - condition: template
      value_template: >
        {{ states('sensor.analyzer_updown') in ['-1', '0', '1'] }}
    action: 
    - service: climate.set_temperature
      data: 
        temperature: >
          {{ states('input_number.bathroom_temp')|float + 0.5 * states('sensor.analyzer_updown')|int }}
      target:
        entity_id: climate.baderomsgulv

