switch: 
  - platform: template
    switches:
      bathroom_generic:
        value_template: "{{states('sensor.baderomsgulv_electric_consumption_w')|int > 50 }}"
        turn_on:
        turn_off:

climate:
  - platform: generic_thermostat
    name: bathroom_temp
    heater: switch.bathroom_onoff
    target_sensor: sensor.bathroom_temp
    target_temp_step: 0.5
    min_temp: 14
    max_temp: 28

template:
  sensor:
  - name: bathroom_temp
    unit_of_measurement: "°C"
    state: "{{ state_attr('climate.baderomsgulv', 'current_temperature') - states('sensor.analyzer_updown')|int * 0.5 }}"

automation:
  - id: '1662913867828'
    alias: Bathroom Analyzer temp adjustment
    trigger: 
      - platform: state
        entity_id: sensor.analyzer_updown
      - platform: template
        value_template: >
          {{ state_attr('climate.bathroom_temp', 'temperature') 
             - states('sensor.analyzer_updown')|int * 0.5 != state_attr('climate.baderomsgulv', 'temperature') }}
    condition: 
    - condition: template
      value_template: >
        {{ states('sensor.analyzer_updown') in ['-1', '0', '1'] }}
    action: 
    - service: climate.set_temperature
      data: 
        temperature: >
          {{ state_attr('climate.bathroom_temp', 'temperature')|float + 0.5 * states('sensor.analyzer_updown')|int }}
      target:
        entity_id: climate.baderomsgulv

