automation:
  - id: '1667483095972'
    alias: someone rings the doorbell
    trigger: 
      - platform: state
        entity_id: siren.doorbell_3
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'off'
    action: 
      - service: notify.mobile_app_titophone
        data:
          message: 'Noen ringte på døra'
          title: 'Rypeveien 11'
          data:
            ttl: 0
            priority: high


