timer:
  easee_timer:
    duration: 00:05:00
    restore: true

input_number:
  ev_battery_pack:
    unit_of_measurement: 'Wh'
    min: 13000
    max: 99000
    step: 500
    mode: box
  ev_max_charge:
    unit_of_measurement: 'W'
    min: 3600
    max: 22000
    step: 225
    mode: box
  ev_charge_steps:
    unit_of_measurement: 'W'
    min: 225
    max: 1800
    mode: box
  ev_min_charge:
    unit_of_measurement: 'W'
    min: 225
    max: 1800
    mode: box
  ev_charge_efficiency:
    unit_of_measurement: '%'
    max: 100
    min: 50
    step: 0.1
    mode: box
  ev_charge_target:
    unit_of_measurement: '%'
    max: 100
    min: 70
    step: 5

input_select: 
  which_car:
    options:
      - Polestar
      - Ioniq
      - Gjestelading
      - Ukjent

input_datetime:
  holiday_until:
    has_date: true
    has_time: false
input_boolean:
  charge_by_clock:
    name: Set charge target by a specific time

input_text: 
  known_soc: 
    max: 50
  
sensor: 
- platform: integration
  name: easee_energy
  source: sensor.easee_power
  method: left
  round: 2
  unit_prefix: k
  unit_time: h

utility_meter:
  easee_usage_hourly:
    source: sensor.easee_energy
    cycle: hourly
  easee_usage_monthly:
    source: sensor.easee_energy
    cycle: monthly

template:
  - sensor:
    - name: easee_power
      unit_of_measurement: W
      device_class: power
      state: '{{ states(''sensor.easee_home_63089_power'')|float(default=0)*1000 }}'
    - name: easee_basic_schedule_start
      state: "{{ state_attr('binary_sensor.easee_home_63089_basic_schedule', 'schedule_chargeStartTime') }}"
    - name: easee_basic_schedule_stop
      state: "{{ state_attr('binary_sensor.easee_home_63089_basic_schedule', 'schedule_chargeStopTime') }}"
    - name: easee_charge_target
      unit_of_measurement: '%'
      state: >
        {% set v = namespace (low=[] ) %}
        {% for forecast in state_attr('weather.rypeveien','forecast') %}
        {% set v.low = v.low + [forecast.templow] %}
        {% endfor %}
        {{ 90 if v.low|min < -5 else 80 }}
  - binary_sensor:
    - name: wants_to_charge
      state: >
        {% set charger_hours = states('sensor.ev_charger_hours')|from_json %}
        {{ (charger_hours|length > 0 and charger_hours[0]|int(default=24) == now().hour) or 
           (charger_hours|length > 1 and charger_hours[1]|int(default=24) == now().hour) or 
           states('sensor.estimate_soc')|float < 20.0 }}
    - name: easee_on
      state: "{{ states('sensor.easee_home_63089_status') == 'charging' }}"
      delay_off: 
        minutes: 2
  - trigger:
      - platform: state
        entity_id: 
          - sensor.rypse2_soc
          - sensor.easee_home_63089_session_energy
    sensor:
    - name: soc_estimate
      unit_of_measurement: "%"
      device_class: battery
      state: >
        {% set last = states('sensor.soc_estimate') %}
        {% set soc = states('sensor.rypse2_soc')|float %}
        {% set soc = (soc if soc > 1 else soc * 100)|int %}
        {% if (trigger.entity_id == 'sensor.rypse2_soc' and 
               trigger.from_state.state != '') %}
          {{ soc }}
        {% elif states('input_select.which_car') == 'Polestar' %}
          {% set session = states('sensor.easee_home_63089_session_energy') | float %}
          {% set efficiency = states('input_number.ev_charge_efficiency') | float %}
          {% set battery = states('input_number.ev_battery_pack') | int %}
          {% set charged = session * 1000 * efficiency / 100 %}
          {% set energy = soc * battery / 100 %}
          {% set soc =  ((energy + charged) / battery  * 100) | round(0) %}
          {% set soc = 95 if soc > 95 else soc  %}
          {% set soc = 100 if (states('input_number.ev_charge_target') == '100') and 
              (states('sensor.easee_home_63089_status') == 'completed') else soc %}
          {{ soc }}
        {% else %}
          {{ last }}
        {% endif %}
      attributes:
        unit_of_measurement: '%'
        last_trigger: '{{ trigger.entity_id }}'
        trigger_from: '{{ trigger.from_state.state }}'
  - trigger:
      - platform: time_pattern
        minutes: "/5"
    sensor:
    - name: easee_current_limit
      unit_of_measurement: A
      state: >
        {% set last = states('sensor.easee_current_limit')|int(default=16) %}
        {% set so_far = states.sensor.energiforbruk_time.state|float * 1000 %}
        {% set power = states.sensor.amshan_power_import.state|float  %}
        {% set seconds_left = 3600 - now().minute * 60 - now().second %}
        {% set easee_power = states('sensor.easee_home_63089_power') | float * 1000 %}
        {% set no_easee_power = 0 if power < easee_power else power - easee_power %}
        {% set restofhour_energy = no_easee_power * seconds_left / 3600 %}
        {% set limit = states('sensor.rest_of_month_energy_limit')|int - 100 %}
        {% set availible = (limit - (so_far  + restofhour_energy)) * 3600 / seconds_left %}
        {% set ev_max = states('input_number.ev_max_charge')|int %}
        {% set ev_min = states('input_number.ev_min_charge')|int %}
        {% set ev_steps = states('input_number.ev_charge_steps')|int %}
        {{ last if now().minute < 5 
           else (ev_max/ ev_steps)|int(default=16) if availible > ev_max
           else 0 if availible < ev_min 
           else (availible / ev_steps)|int + 1  }}

automation:
  - id: '1703798116334'
    alias: trigger easee_timer
    trace:
      stored_traces: 15
    trigger:
      - platform: time_pattern
        minutes: "0"
      - platform: state
        entity_id: sensor.easee_home_63089_status
        from: 'disconnected'
      - platform: state
        entity_id: input_select.which_car
      - platform: state
        entity_id: sensor.ev_charger_hours
      - platform: numeric_state
        entity_id: sensor.easee_home_63089_power
        above: 1
    condition:
      - condition: state
        entity_id: timer.easee_timer
        state: idle
    action:
      - service: timer.start
        target:
          entity_id: timer.easee_timer

  - id: '1691265354404'
    alias: Select which car to charge or not
    trace:
      stored_traces: 15
    trigger:
    - platform: state
      entity_id: sensor.easee_home_63089_status
      to: 'disconnected'
    - platform: state
      entity_id: sensor.easee_home_63089_status
      from: 'disconnected'
    - platform: state
      entity_id: 
        - person.amalie_johansen
        - device_tracker.polestar
      to: 'home'
    - platform: state
      entity_id: sensor.polestar_8958_charger_connection_status
      to: 'Connected'
    action:
      - service: input_select.select_option
        data:
          option: >
            {% set last = states('input_select.which_car') %}
            {% set unconnected = is_state ('sensor.easee_home_63089_status', 'disconnected') %}
            {% set ah_home = is_state('person.amalie_johansen', 'home') %}
            {% set rp2_connected = is_state('sensor.polestar_8958_charger_connection_status', 'Connected') %}
            {% set rp2_home = states('device_tracker.polestar') == 'home' %}
            {{ 'Ukjent' if unconnected else 
               'Polestar' if rp2_connected and rp2_home else 
               'Ioniq' if ah_home else
               last }}
        target:
          entity_id: input_select.which_car
      - if:
        - condition: state
          entity_id: timer.easee_timer
          state: idle
        then:
        - service: timer.start
          data: {}
          target:
            entity_id: timer.easee_timer

  - id: '1691611803561'
    alias: resume Easee charger if set to charge
    trace:
      stored_traces: 15
    trigger: 
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.easee_timer
      - platform: numeric_state
        entity_id: sensor.easee_current_limit
        above: 6
      - platform: state
        entity_id: input_select.which_car
    condition:
      - condition: numeric_state
        entity_id: sensor.easee_home_63089_power
        below: 1
      - condition: numeric_state
        entity_id: sensor.easee_current_limit
        above: 6
      - condition: or
        conditions: 
          - condition: state
            entity_id: input_select.which_car
            state: Ioniq
          - condition: state
            entity_id: input_select.which_car
            state: Gjestelading
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.which_car
                state: Polestar
              - condition: or
                conditions: 
                - condition: numeric_state
                  entity_id: sensor.polestar_8958_battery_charge_level
                  below: 20
                - condition: template
                  value_template: >
                    {% set hours = states('sensor.ev_charger_hours') %}
                    {% set hours = [] if hours in ('unavailable') else hours|from_json %}
                    {{ hours|length > 0 and hours[0] <= now().hour }}
    action:
      - service: easee.action_command
        data:
          device_id: a20dd2805745c03f8ecfdb606254114c
          action_command: resume
      - service: timer.start
        data: {}
        target:
          entity_id: timer.easee_timer

  - id: '1691611803661'
    trace:
      stored_traces: 15
    alias: Pause Easee charger if not set to charge
    trigger: 
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.easee_timer
      - platform: numeric_state
        entity_id: sensor.easee_current_limit
        below: 7
      - platform: numeric_state
        entity_id: sensor.polestar_8958_battery_charge_level
        above: 20
    condition:
      - condition: numeric_state
        entity_id: sensor.easee_home_63089_power
        above: 1
      - condition: or
        conditions: 
          - condition: numeric_state
            entity_id: sensor.easee_current_limit
            below: 7
          - condition: state
            entity_id: input_select.which_car
            state: Ukjent
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.which_car
                state: Polestar
              - condition: template
                value_template: >
                  {% set hours = states('sensor.ev_charger_hours') %}
                  {% set hours = [now().hour] if hours in ('unavailable') else hours|from_json %}
                  {{ hours|length == 0 or hours[0] > now().hour }}
              - condition: numeric_state
                entity_id: sensor.polestar_8958_battery_charge_level
                above: 20
    action:
      - service: easee.action_command
        data:
          device_id: a20dd2805745c03f8ecfdb606254114c
          action_command: pause
      - service: timer.start
        data: {}
        target:
          entity_id: timer.easee_timer
      - if:
        - condition: state
          entity_id: input_select.which_car
          state: "Ukjent"
        then: 
          - service: notify.mobile_app_xq_au52
            data:
              message: Ser ut som ukjent bil har koblet seg til laderen.
              title: Easeelader @ rypeveien
              data:
                priority: high

  - id: '1657636827656'
    alias: Easee charger throttling
    trace:
      stored_traces: 15
    description: ''
    trigger:
      - platform: state
        entity_id: sensor.easee_current_limit
    condition:
      - condition: numeric_state
        entity_id: sensor.easee_current_limit
        above: 6
      - condition: state
        entity_id: sensor.easee_home_63089_status
        state: charging
      - condition: template
        value_template: "{{ trigger.from_state.state|int(default=16) != trigger.to_state.state|int(default=16) }}"
    action: 
      - service: easee.set_charger_dynamic_limit
        data:
          current: "{{ states('sensor.easee_current_limit') }}"
          device_id: a20dd2805745c03f8ecfdb606254114c
      - service: timer.start
        target:
          entity_id: timer.easee_timer

  - id: '1680332588223'
    trace:
      stored_traces: 15
    alias: cache known soc and timestamp when ev_charge_state changes
    trigger: 
      - platform: state
        entity_id: sensor.ev_charge_state
    action: 
      - service: input_text.set_value
        data: 
          value: >
            {% set energy = 0 if states('sensor.easee_home_63089_status') == 'disconnected' else 
                            states('sensor.easee_home_63089_session_energy')| int %}
            {{ {'energy': energy, 
                'soc': states('sensor.ev_charge_state'),
                'ts': now().timestamp()|int }|to_json }}
        target: 
          entity_id: input_text.known_soc

  - id: '1689617707052'
    alias: reset charge target when disconnects
    trigger: 
      - platform: state
        entity_id: sensor.easee_home_63089_status
        to: disconnected
    condition:
      - condition: numeric_state
        entity_id: input_number.ev_charge_target
        above: sensor.easee_charge_target
    action: 
      - service: input_number.set_value
        data: 
          value: "{{ states('sensor.easee_charge_target') }}"
        target: 
          entity_id: input_number.ev_charge_target

  - id: '1695420496433'
    trace:
      stored_traces: 15
    alias: easee draws power when it says it ready to charge
    description: "Stops easee charger if it starts charging when it says its not charging"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.easee_timer
    condition:
      - condition: numeric_state
        entity_id: sensor.easee_home_63089_power
        above: 1
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.easee_home_63089_status
            state: charging
    action:
      - service: easee.action_command
        data:
          device_id: a20dd2805745c03f8ecfdb606254114c
          action_command: pause
      - service: notify.mobile_app_xq_au52
        data:
          message: Ser ut som Easee lader uten grunn. Har forsøkt å stoppe det
          title: Easeelader @ rypeveien
      - service: timer.start
        target:
          entity_id: timer.easee_timer

