input_text: 
  max_3hour_month_usage:
    name: Max energy usage 3 hours this month
    max: 40

input_number:
  last_energy_reading:
    name: Energy reading last hour
    max: 200000
    min: 0
    unit_of_measurement: "kWh"

#sensor:
#- platform: integration
#  source: sensor.amshan_power_import
#  method: left
#  round: 2
#  unit_prefix: k
#  unit_time: h
    
template:
  sensor:
  - name: power_controlled
    unit_of_measurement: W
    device_class: power
    state: >
      {{ states('sensor.vv_tank_electric_consumption_w')|int(default=0)
         + states('sensor.vv_kjeller_power')|int(default=0)
         + states('sensor.shellyvask_power')|int(default=0)
         + states('sensor.torketrommel_power')|int(default=0)
         + states('sensor.easee_power')|int(default=0) }}
  - name: power_uncontrolled
    unit_of_measurement: W
    device_class: power
    state: >
      {% set uncontrolled =  states('sensor.power_usage')|int(default=0)
       - states('sensor.power_controlled')|int(default=0) %}
      {{ uncontrolled if uncontrolled > 0 else 0 }}
  - name: power_monitored
    unit_of_measurement: W
    device_class: power
    state: >
      {{ states('sensor.vpoppe_power')|int(default=0)
       + states('sensor.vpnede_power')|int(default=0)
       + states('sensor.kjoleskap_electric_consumption_w')|int(default=0)
       + states('sensor.inngangstikk_power')|int(default=0)
       + states('sensor.server_power')|int(default=0)
       + states('sensor.baderomsgulv_electric_consumption_w')|int(default=0)
       + states('sensor.shellyfrys_power_2')|int(default=0)
       + states('sensor.shellykjol_switch_0_power')|int(default=0)
       + states('sensor.adax_guest_power')|int(default=0)
       + states('sensor.adax_syrom_power')|int(default=0)
       + states('sensor.fa_adax_power')|int(default=0) }}
  - name: power_unmonitored
    unit_of_measurement: W
    device_class: power
    state: >
      {% set unmonitored =  states('sensor.power_uncontrolled')|int(default=0)
       - states('sensor.power_monitored')|int(default=0) %}
      {{ unmonitored if unmonitored > 0 else 0 }}
  - name: power_usage
    unit_of_measurement: W
    device_class: power
    state: >
      {{ states('sensor.amshan_power_import')|int(default=0)
         + states('sensor.pvlogger_power')|int(default=0)
         - states('sensor.amshan_power_export')|int(default=0) }}
  - unique_id: power_in_or_out
    unit_of_measurement: 'W'
    state: '{{ states.sensor.amshan_power_import.state|int -  states.sensor.amshan_power_export.state|int }}'
    attributes:
      friendly_name: 'Kraft forbrukt fra eller levert til nettet'
  - name: last_energy_reading
    unit_of_measurement: 'kWh'
    state: >
      {% set last_energy_reading = states('input_number.last_energy_reading') %}
      {{ last_energy_reading }}
  - name: energy_this_hour_estimate
    unit_of_measurement: 'kWh'
    state: >
      {% set this_hour = states('sensor.energy_this_hour_estimate') %}
      {% set last_energy_reading = states('input_number.last_energy_reading') %}
      {% set tdiff = now().timestamp() - states.input_number.last_energy_reading.last_updated.timestamp() %}
      {{ ((states.sensor.energiforbruk.state|float - last_energy_reading|float) * 3600 / tdiff)|round(3) if tdiff > 60 else this_hour }}
  - name: max_3hour_month_usage_average
    unit_of_measurement: 'kWh'
    state: >
      {% set max3 = states('input_text.max_3hour_month_usage')|from_json %}
      {% set this = states.sensor.energy_this_hour_estimate.state|float %}
      {% set max3 = ((max3 + [this])|sort(1))[:3] %}
      {% set v = namespace (sum=0) %}
      {% for i in range (max3|length) %}
      {%   set v.sum = v.sum + max3[i] %}
      {% endfor %}
      {{ (v.sum / max3|length)|round(3) }}

automation:
  - id: '1655705659488'
    alias: 'Update max usage this month'
    description: ''
    trigger:
    - platform: time_pattern
      minutes: '59'
      seconds: '59'
    condition: []
    variables: 
      saved: '{{ states(''input_number.last_energy_reading'')|float(default=0) }}'
      asofnow: '{{ states(''sensor.energiforbruk'')|float(default=0) }}'
      max3: >
        {% set max3 = states('input_text.max_3hour_month_usage') %}
        {{ ('[]' if (max3 == 'unknown' or states.input_text.max_3hour_month_usage.last_updated.month != now().month) else max3)|from_json }}
    action:
    - service: input_number.set_value
      data: 
        value: '{{ asofnow }}'
      target: 
        entity_id: input_number.last_energy_reading
    - service: input_text.set_value
      data: 
        value: >
          {{ (((max3 + [ (asofnow - saved)|round(3)])|sort(1))[:3])|to_json}}
      target: 
        entity_id: input_text.max_3hour_month_usage

