template:
  - sensor: 
    - name: fa_tracker_activity_detected
      state: "{% set track = states('sensor.fa_tracker') %} {{ states('sensor.'+track+'_detected_activity') }}"
    - name: fa_device_tracker
      state: >
        {% set last = states('sensor.fa_device_tracker') %}
        {% set track = states('sensor.fa_tracker') %} 
        {% set track_state = states('device_tracker.'+track) %}
        {% set track_activity = states('sensor.'+track+'_detected_activity') %}
        {{ last if track_state == 'not_home' and track_activity == 'still' 
           else track_state }}

  - trigger: 
      - platform: state
        entity_id:
          - sensor.faa3phone_detected_activity
          - sensor.titophone_detected_activity
    sensor:
      - name: fa_tracker
        state: >
          {% set from = trigger.from_state.state %}
          {% set to = trigger.to_state.state %}
          {% set last = states('sensor.fa_tracker') %}
          {{ last if from in ['unavailable'] or to in ['unavailable'] else
             trigger.entity_id.split (".")[1].split("_")[0] }}

automation:
  - id: '1645796029028'
    alias: FA Hjemme eller borte
    description: ''
    trigger:
    - platform: state
      entity_id:
      - sensor.fa_device_tracker
    condition: []
    action:
    - service: device_tracker.see
      data:
        dev_id: fa_tracker
        location_name: "{{ states('sensor.fa_device_tracker') }}"
    mode: single
