timer:
  frigate_silencer:
    duration: 00:05:00
    restore: true

input_text: 
  frigate_last: 
    max: 255

automation:
  - id: '1660990404933'
    alias: Frigate notify
    trigger:
      platform: mqtt
      topic: frigate/events
    variables:
      ext_address: !secret ext_address
      last_frigate: "{{ states('input_text.frigate_last')|from_json }}"
      trigger_payload: "{{trigger.payload_json['after'] }}"
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: "off"
    action:
      - choose:
        - conditions: 
          - condition: state
            entity_id: timer.frigate_silencer
            state: idle
          - condition: template
            value_template: "{{ last_frigate.msg != trigger_payload.id }}"
          sequence:
          - service: timer.start
            entity_id: timer.frigate_silencer
          - service: notify.mobile_app_xq_au52
            data_template:
              message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
              data:
                image: '{{ ext_address }}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
                tag: '{{trigger.payload_json["after"]["id"]}}'
                when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        default:
        - service: input_text.set_value
          target:
            entity_id: input_text.frigate_last
          data:
            value: >
              {% set last = states('input_text.frigate_last')|from_json %}
              {% set count = last.count + 1 if last.count is defined else 1 %}
              {% set msg = trigger.payload_json["after"]["label"] %}
              {% set id = trigger.payload_json["after"]["id"] %}
              {% set ts = trigger.payload_json["after"]["start_time"]|int %}
              {{ { 'msg': msg, 'id': id, 'count': count, 'ts': ts }|to_json }}

  - id: '1660990404934'
    alias: Frigate timer
    trigger:
      platform: event
      event_type: timer_finished
      event_data:
        entity_id: timer.frigate_silencer
    variables:
      ext_address: !secret ext_address
      last_frigate: "{{ states('input_text.frigate_last')|from_json }}"
    action:
      - choose:
        - conditions: 
          - condition: template
            value_template: >
              {% set count = last_frigate.count if last_frigate.count is defined else 0 %}
              {{ count > 1 }}
          sequence:
          - service: timer.start
            entity_id: timer.frigate_silencer
          - service: notify.mobile_app_xq_au52
            data_template:
              message: 'A {{last_frigate.msg}} was detected {{ last_frigate.count }} time(s).'
              data:
                image: '{{ ext_address }}/api/frigate/notifications/{{last_frigate.id}}/thumbnail.jpg?format=android'
                tag: '{{last_frigate.id}}'
                when: '{{last_frigate.ts}}'
      - service: input_text.set_value
        target:
          entity_id: input_text.frigate_last
        data:
          value: >
            {{ { 'msg': last_frigate.msg, 'id': last_frigate.id, 'ts': last_frigate.ts, 'count': 0}|to_json }}

  - id: '1661326781305'
    alias: Turn frigate recordings on or off
    trigger: 
      platform: template
      value_template: "{{ (states('lock.dana_oppe') == 'locked' or states('binary_sensor.anyone_home') == 'off') != (states('switch.inngang_recordings') == 'on') }}"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.inngang_recordings

