climate:
  - platform: generic_thermostat
    name: garage_heating
    heater: switch.shellyplugggarasjevarme
    target_sensor: sensor.garasjen_temperature
    target_temp_step: 1
    min_temp: 5
    max_temp: 17

automation: 
  - id: '1668631031058'
    alias: Turn of heating when work is done
    trigger: 
      - platform: template
        value_template: >
          {{ state_attr('climate.garage_heating', 'temperature') > 5
             and now().hour >= 21 }}
    action:
    - service: climate.set_temperature
      data:
        temperature: 5
      target:
        entity_id: climate.garage_heating


