input_boolean:
  garage_comfort: 
    name: Turn on/off comfort temp in garage
    icon: mdi:heat-pump-outline

climate:
  - platform: generic_thermostat
    name: garage_heating
    heater: switch.shellyplugggarasjevarme
    target_sensor: sensor.garasjen_temperature
    target_temp_step: 1
    min_temp: 5
    max_temp: 17

automation: 
  - id: '1668631031058'
    alias: Turn on/off heating in the garage
    trigger: 
      - platform: state
        entity_id: input_boolean.garage_comfort
      - platform: time
        at: "20:30:00"
        id: turn_off
    action:
    - choose: 
      - conditions:
        - condition: trigger
          id: turn_off
        sequence:
        - if: 
          - condition: numeric_state
            entity_id: climate.garage_heating
            attribute: temperature
            above: 5
          then:
            - service: climate.set_temperature
              data:
                temperature: 5
              target:
                entity_id: climate.garage_heating
        - if:
          - condition: state
            entity_id: input_boolean.garage_comfort
            state: "on"
          then:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.garage_comfort
      - conditions:
        - condition: template
          value_template: "{{ trigger.from_state.state == 'on' and trigger.to_state.state == 'off' }}"
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 5
          target:
            entity_id: climate.garage_heating
      - conditions:
        - condition: template
          value_template: "{{ trigger.from_state.state == 'off' and trigger.to_state.state == 'on' }}"
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 12
          target:
            entity_id: climate.garage_heating
