automation: 
  - id: '1658673475311'
    alias: 'Climate VP Oppe Start cooling '
    description: ''
    trigger:
    - type: temperature
      platform: device
      device_id: ebea6b2a64973129f827b002460b82b8
      entity_id: sensor.netatmo_rypeveien_netatmo_temperature
      domain: sensor
      above: 25
      for:
        hours: 0
        minutes: 30
        seconds: 0
    condition:
    - condition: numeric_state
      entity_id: sensor.pvlogger_power
      above: '2000'
    - condition: device
      device_id: c26046a34e1fac9463da2e9fe2b62a84
      domain: climate
      entity_id: climate.vp_oppe
      type: is_hvac_mode
      hvac_mode: 'off'
    - type: is_not_open
      condition: device
      device_id: 6bc64238a27390d5438678e684f642e6
      entity_id: binary_sensor.verandador_contact
      domain: binary_sensor
      for:
        hours: 0
        minutes: 30
        seconds: 0
    - type: is_not_open
      condition: device
      device_id: ad3160c2bf2ac77b821e2f52e3d26ab9
      entity_id: binary_sensor.inngangsdor_door_window
      domain: binary_sensor
      for:
        hours: 0
        minutes: 30
        seconds: 0
    action:
    - device_id: c26046a34e1fac9463da2e9fe2b62a84
      domain: climate
      entity_id: climate.vp_oppe
      type: set_hvac_mode
      hvac_mode: cool
    - service: climate.set_temperature
      data:
        temperature: 25
      target:
        entity_id: climate.vp_oppe
    mode: single
  - id: '1658673749726'
    alias: Climate VP oppe Turn off when idle for 20 hours
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.vpoppe_power
      for:
        hours: 20
        minutes: 0
        seconds: 0
      below: '50'
    condition:
    - condition: not
      conditions:
      - condition: device
        device_id: c26046a34e1fac9463da2e9fe2b62a84
        domain: climate
        entity_id: climate.vp_oppe
        type: is_hvac_mode
        hvac_mode: 'off'
    action:
    - device_id: c26046a34e1fac9463da2e9fe2b62a84
      domain: climate
      entity_id: climate.vp_oppe
      type: set_hvac_mode
      hvac_mode: 'off'
    mode: single

