automation: 
  - id: '1637565436384'
    alias: Compressor
    description: ''
    trigger:
    - platform: template
      value_template: >
        {% set hour = now().hour %}
        {% set last = states.switch.shellypluggkompressor.last_updated.timestamp() %}
        {% set switch = states('switch.shellypluggkompressor') %}
        {% set wants = 'on' if hour >= 10 and hour < 22 else 'off' %}
        {{ now().timestamp() - last > 1800 and switch != wants }}
      id: daily_schedule
    action:
      - service: switch.toggle
        target:
          entity_id: switch.shellypluggkompressor
    mode: single
