automation:
  - id: '1659781447148'
    alias: update laptoplader power
    description: ''
    trigger:
    - platform: state
      entity_id: switch.laptoplader
      id: state_trigger
    - platform: template
      value_template: >
        {{ states.switch.laptoplader.state == 'on' 
           and now().timestamp() - states.switch.laptoplader.last_updated.timestamp() > 300 and
           now().minute % 5 == states.sensor.laptoplader_electric_consumption_w.last_updated.minute % 5 }}
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: state_trigger
        sequence: 
        - delay: 
            seconds: 10
    - service: zwave_js.refresh_value
      data:
        entity_id: sensor.laptoplader_electric_consumption_w
        refresh_all_values: true
    mode: single

  - id: '1617914362468'
    alias: Lading av FA Laptop
    description: ''
    trigger:
    - platform: template
      value_template: '{{ states(''sensor.fajlat2_battery'')|int(default=50) > 80 }}'
    - platform: template
      value_template: '{{ states(''sensor.fajlat2_battery'')|int(default=50) < 20 }}'
    - platform: template
      value_template: '{{ states(''sensor.laptoplader_electric_consumption_w'')|float(default=0) <= 5}}'
    - platform: template
      value_template: '{{ now().timestamp() - states.switch.laptoplader.last_updated.timestamp() > (8 * 3600) }}'
      id: 8hour
    - platform: template
      value_template: >
        {% set sensor = states.sensor.fajlat2_battery %}
        {{ now().timestamp() - sensor.last_updated.timestamp() > 600 
           if sensor.state is defined else false }}
      id: lost_connection
    condition: []
    action:
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ states(''sensor.fajlat2_battery'')|int(default=50) < 20 }}'
        - condition: device
          type: is_off
          device_id: 381b70ad0b92687d94def574c24d0812
          entity_id: switch.laptoplader
          domain: switch
        sequence:
        - type: turn_on
          device_id: 381b70ad0b92687d94def574c24d0812
          entity_id: switch.laptoplader
          domain: switch
      - conditions:
        - condition: template
          value_template: '{{ states(''sensor.fajlat2_battery'')|int(default=50) > 80 }}'
        - condition: template
          value_template: '{{ state_attr(''sensor.fajlat2_battery'', ''status'') != ''Discharging'' }}'
        - condition: device
          type: is_on
          device_id: 381b70ad0b92687d94def574c24d0812
          entity_id: switch.laptoplader
          domain: switch
        sequence:
        - type: turn_off
          device_id: 381b70ad0b92687d94def574c24d0812
          entity_id: switch.laptoplader
          domain: switch
      - conditions:
        - condition: template
          value_template: >
            {{ now().timestamp() - as_timestamp(states.sensor.fajlat2_battery.last_changed) > 600 }}
        sequence:
          - choose:
            - conditions:
              - condition: device
                type: is_off
                device_id: 381b70ad0b92687d94def574c24d0812
                entity_id: switch.laptoplader
                domain: switch
              sequence:
              - type: turn_on
                device_id: 381b70ad0b92687d94def574c24d0812
                entity_id: switch.laptoplader
                domain: switch
            - conditions:
              - condition: template
                value_template: '{{ states(''sensor.laptoplader_electric_consumption_w'')|float(default=0) <= 5 }}'
              sequence:
              - type: turn_off
                device_id: 381b70ad0b92687d94def574c24d0812
                entity_id: switch.laptoplader
                domain: switch
            default: []
      default: []
    mode: single


