automation:
  - id: '1617914362468'
    alias: Lading av FA Laptop
    description: ''
    trigger:
    - platform: template
      value_template: "{{ states('sensor.fajlat2_battery')|int(default=50) > 80 }}"
      id: high
    - platform: template
      value_template: "{{ states('sensor.fajlat2_battery')|int(default=50) < 20 }}"
      id: low
    - platform: template
      value_template: "{{ states('sensor.shellyplugglaptoplader_power')|float(default=0) <= 5}}"
      id: charged
    - platform: template
      value_template: >
        {% set low = states('sensor.fajlat2_battery')|int(default=50) < 60 %}
        {% set old = (now().timestamp() - as_timestamp(states.sensor.fajlat2_battery.last_updated)) > 900 %}
        {{ low and old }}
      id: offline
    condition: []
    action:
    - choose:
      - conditions:
        - condition: or 
          conditions:
            - condition: trigger
              id: high
            - condition: trigger
              id: charged
        sequence:
        - type: turn_off
          device_id: ab56794fc68ab28aa5d9d537c63b9306
          entity_id: switch.shellyplugglaptoplader
          domain: switch
      - conditions:
        - condition: or
          conditions:
            - condition: trigger
              id: low
            - condition: trigger
              id: offline
        sequence:
        - type: turn_on
          device_id: ab56794fc68ab28aa5d9d537c63b9306
          entity_id: switch.shellyplugglaptoplader
          domain: switch
    mode: single


