automation:
  - id: '1642107767643'
    alias: Vaskemaskin ferdig
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.vaskemaskin_on
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: sonos.snapshot
      data:
        entity_id: media_player.stue
        with_group: true
    - service: media_player.volume_set
      data:
        volume_level: 0.2
      target:
        entity_id: media_player.stue
    - service: tts.google_translate_say
      data:
        entity_id: media_player.stue
        message: Vaskemaskinen er ferdig
        language: 'no'
    - delay: 1
    - wait_template: "{{ is_state('media_player.stue', 'paused') }}"
    - service: media_player.volume_set
      data:
        volume_level: "{{ mediaplayer_volume_level }}"
      target:
        entity_id: media_player.stue
    - service: sonos.restore
      data:
        entity_id: media_player.stue
        with_group: true
    variables: 
      mediaplayer_volume_level: "{{ state_attr('media_player.stue', 'volume_level') }}"
    mode: single

  - id: '1642367007216'
    alias: Tørketrommel er ferdig
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.torketrommel_on
      from: 'on'
      to: 'off'
    condition: []
    action:
      - service: sonos.snapshot
        data:
          entity_id: media_player.stue
          with_group: true
      - service: media_player.volume_set
        data:
          volume_level: 0.2
        target:
          entity_id: media_player.stue
      - service: tts.google_translate_say
        data:
          entity_id: media_player.stue
          message: Tørketrommelen er ferdig
          language: 'no'
      - delay: 1
      - wait_template: "{{ is_state('media_player.stue', 'paused') }}"
      - service: media_player.volume_set
        data:
          volume_level: "{{ mediaplayer_volume_level }}"
        target:
          entity_id: media_player.stue
      - service: sonos.restore
        data:
          entity_id: media_player.stue
          with_group: true
    variables: 
      mediaplayer_volume_level: "{{ state_attr('media_player.stue', 'volume_level') }}"
    mode: single


  - id: '1672754483369'
    alias: Sikring til vaskemaskin og tørketrommel er gått
    description: ''
    trigger:
    - platform: template
      value_template: >
        {% set check = now().timestamp() - 300 %}
        {{ states('binary_sensor.torketrommel_on') == 'on' and 
           states('binary_sensor.vaskemaskin_on') == 'on' and
           states.sensor.stikk_torketrommel_power.last_updated.timestamp() < check and
           states.sensor.stikk_vaskemaskin_power.last_updated.timestamp() < check }}
    condition: []
    action:
    - service: sonos.snapshot
      data:
        entity_id: media_player.stue
        with_group: true
    - service: media_player.volume_set
      data:
        volume_level: 0.2
      target:
        entity_id: media_player.stue
    - service: tts.google_translate_say
      data:
        entity_id: media_player.stue
        message: Unnskyld, men jeg lurer på om sikringen til vaskemaskin og tørketrommel har gått
        language: 'no'
    - delay: 1
    - wait_template: "{{ is_state('media_player.stue', 'paused') }}"
    - service: media_player.volume_set
      data:
        volume_level: "{{ mediaplayer_volume_level }}"
      target:
        entity_id: media_player.stue
    - service: sonos.restore
      data:
        entity_id: media_player.stue
        with_group: true
    variables: 
      mediaplayer_volume_level: "{{ state_attr('media_player.stue', 'volume_level') }}"
    mode: single

