input_text:
  nordpool_today:
    max: 255
  nordpool_tomorrow:
    max: 255
  nordpool_month: 
    max: 255

rest:
  - resource: "https://www.nordpoolgroup.com/api/marketdata/page/23?currency=,NOK,NOK,EUR"
    scan_interval: 129600
    sensor: 
      - name: nordpool api
        value_template: '{{ value_json.data.DateUpdated }}'
        json_attributes_path: $.data
        json_attributes: 
          - "Rows"


template:
  - sensor:
    - name: nordpool_subsides
      unit_of_measurement: "NOK/kWh"
      state: >
        {% set avg = states('sensor.nordpool_month_average') %}
        {{ 'unknown' if avg in ['unknown', 'unavailable'] else 
            0 if  avg|float <= 0.7 else 
            ((avg|float - 0.7) * 0.9 * 1.25)|round(4) }}
    - name: nordpool_month_average
      unit_of_measurement: "NOK/kWh"
      state: >
        {% set month = states('input_text.nordpool_month') %}
        {% set month = [] if month in ['unknown', 'unavailable'] else month|from_json %}
        {% set tomorrow = states('input_text.nordpool_tomorrow') %}
        {% set daymon = now().day if now().month != (now() + timedelta(days=1)).month else now().day + 1 %}
        {% set month = month if tomorrow in ['unknown', 'unavailable', '[]'] or daymon > now().day 
                       else [ tomorrow|from_json|average] + month  %}
        {% set mlength = 31 if now().month in [1, 3, 5, 7, 8, 10, 12] else
                         30 if now().month in [4, 6, 9, 11] else
                         29 if now().year % 4 == 0 else 28 %}
        {{ 'unknown' if month|length == 0 else
           ((month[:mlength]|average + month[:daymon]|average)/2)|round(4) }}
  - binary_sensor:
    - name: nordpool_official
      state: "{{ states.sensor.nordpool_api.attributes.Rows[0].Columns[0].IsOfficial }}"

  - trigger: 
    - platform: template
      value_template: >
        {% set rows =  state_attr('sensor.nordpool_api', 'Rows') %}
        {{ false if rows == None else as_datetime(rows[0].StartTime).day == now().day}}
    sensor:
    - name: nordpool_today
      state: >
        {% set var = namespace (price=[]) %}
        {% set rows = state_attr('sensor.nordpool_api', 'Rows') %}
        {% for row in rows -%}
          {% set end = as_datetime(row.EndTime) %}
          {% set start = as_datetime(row.StartTime) %}
          {% if (end.timestamp() - start.timestamp() == 3600) %}
            {%- for column in row.Columns -%}
              {% if column.Name == 'Kr.sand' -%}
                {% set price = (column.Value|replace(',', '.')|float/1000)|round(4) %}
                {% set var.price = var.price + [ price ] %}
              {% endif %}
            {%- endfor %}
          {% endif %}
        {%- endfor %}
        {{ var.price|to_json }}
  - trigger: 
    - platform: template
      value_template: >
        {% set rows =  state_attr('sensor.nordpool_api', 'Rows') %}
        {{ false if rows == None else 
           as_datetime(rows[0].StartTime).day == (now() + timedelta(days=1)).day }}
    - platform: time
      at: 00:00
    sensor:
    - name: nordpool_tomorrow
      state: >
        {% set var = namespace (price=[]) %}
        {% set rows = state_attr('sensor.nordpool_api', 'Rows') %}
        {% for row in rows %}
          {% set end = as_datetime(row.EndTime) %}
          {% set start = as_datetime(row.StartTime) %}
          {% if (end.timestamp() - start.timestamp() == 3600) and 
              (start.day != now().day) %}
            {% for column in row.Columns %}
              {% if column.Name == 'Kr.sand' %}
                {% set price = (column.Value|replace(',', '.')|float/1000)|round(4) %}
                {% set var.price = var.price + [ price ] %}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
        {{ var.price|to_json }}

automation:  
  - id: '1654892652238'
    alias: 'nordpool price update'
    trigger: 
    - platform: template
      value_template: >
        {% set last = states('sensor.nordpool_api') %}
        {% set updated = states.sensor.nordpool_api.last_updated if last not in ['unknown', 'unavailable'] else (now() - timedelta(days=1)) %}
        {% set last = as_datetime(last) if last not in ['unknown', 'unavailable'] else (now() - timedelta(days=1)) %}
        {{ (last.day != now().day or (last.hour < 13 and updated.hour < 14)
            or states('input_text.nordpool_tomorrow') in  ['', 'unknown', '[]']) 
            and (now().minute % 15) == 8 and now().hour >= 13 
            and state_attr('automation.nordpool_price_update', 'current') == 0 }}
    condition: []
    action: 
    - delay: 
        seconds: '{{ range(1,1140)|random|int }}'
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.nordpool_api

  - id: '1665404895206'
    alias: 'nordpool tomorrow cache'
    trigger: 
    - platform: state
      entity_id: sensor.nordpool_api
    condition: []
    action: 
    - service: input_text.set_value
      target:
        entity_id: input_text.nordpool_tomorrow
      data: 
        value: >
          {% set l = namespace(prices=[]) %}
          {% for row in states.sensor.nordpool_api.attributes.Rows %}
            {% if (as_datetime(row.EndTime).timestamp() - as_datetime(row.StartTime).timestamp() == 3600) %}
              {% for column in row.Columns %}
                {% if column.Name  == 'Kr.sand' %}
                  {% set l.prices = l.prices +
                    [(column.Value|replace(" ", "")|replace(",",".")|float/1000)|round(4)] %}
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}
          {{ l.prices|to_json }}
#          To list names for the different sones. Use template in Developer tools to list them
#          {% for cols in state_attr('sensor.nordpool_api', 'Rows')[0].Columns %} {{ cols.Name }} {% endfor %}

  - id: '1665405646854'
    alias: 'nordpool rotate cache at midnight'
    trigger: 
    - platform: time
      at: "00:00"
    condition: []
    action: 
    - service: input_text.set_value
      target:
        entity_id: input_text.nordpool_today
      data: 
        value: "{{ states('input_text.nordpool_tomorrow')}}"
    - service: input_text.set_value
      target:
        entity_id: input_text.nordpool_tomorrow
      data: 
        value: "[]"
    - service: input_text.set_value
      target:
        entity_id: input_text.nordpool_month
      data: 
        value: >
          {% set last = states('input_text.nordpool_month') %}
          {% set month = now().month %}
          {% set length = 31 if month in [1, 3, 5, 7, 8, 10, 12]
                     else 30 if month in [4, 6, 9, 11 ]
                     else 29 if now().year % 4 == 0
                     else 28 %}
          {% set last = [] if last in ['unknown', 'unavailable'] else last|from_json %}
          {% set today = states('input_text.nordpool_today') %}
          {% set today = [] if today in ['unknown', 'unavailable'] else [ today|from_json|average|round(4) ] %}
          {{ ((today + last)[:length])|to_json }}
