rest:
  - resource: "https://www.nordpoolgroup.com/api/marketdata/page/23?currency=,NOK,NOK,EUR"
    scan_interval: 129600
    sensor: 
      - name: nordpool api
        value_template: '{{ value_json.data.DateUpdated }}'
        json_attributes_path: $.data
        json_attributes: 
          - "Rows"


template:
  - sensor:
      - name: nordpool_tomorrow
        state: >
          {% set v = namespace(tomorrow=[]) %}
          {% set rows = state_attr('sensor.nordpool_api', 'Rows') %}
          {% if rows|length > 0 and 
            as_datetime(rows[0].StartTime).day == (now() + timedelta(days=1)).day %}
            {% for row in rows %}
            {% for col in row.Columns %}
            {% if col.Name == 'Kr.sand' %}
            {% set v.tomorrow = v.tomorrow + [ (col.Value|replace(',', '.')|replace(' ', '')|float/1000)|round(4) ] 
               if v.tomorrow|length == as_datetime(row.StartTime).hour else v.tomorrow %}
            {% endif %}
            {% endfor %}
            {% endfor %}
          {% endif %}
          {{ v.tomorrow }}
#          To list names for the different sones. Use template in Developer tools to list them
#          {% for cols in state_attr('sensor.nordpool_api', 'Rows')[0].Columns %} {{ cols.Name }} {% endfor %}

  - trigger:
      - platform: state
        entity_id: sensor.nordpool_tomorrow
    sensor:
      - name: nordpool_today
        state: >
          {% set last = states('sensor.nordpool_today') %}
          {% set new = trigger.from_state.state %}
          {{ new if trigger.to_state.state == '[]' else last }}
  - trigger:
      - platform: state
        entity_id: sensor.nordpool_today
    sensor:
      - name: nordpool_month
        state: >
          {% set last = states('sensor.nordpool_month')|from_json %}
          {% set month = now().month %}
          {% set length = 31 if month in [1, 3, 5, 7, 8, 10, 12]
                     else 30 if month in [4, 6, 9, 11 ]
                     else 29 if now().year % 4 == 0
                     else 28 %}
          {{ ([ states('sensor.nordpool_today')|from_json|average|round(4) ] + last)[:length] }}

automation:  
  - id: '1654892652238'
    alias: 'nordpool price update'
    trigger: 
    - platform: template
      value_template: >
        {{ as_datetime(states('sensor.nordpool_api')).day != now().day and
          (now().minute % 30) == 18 and now().hour >= 13 and 
          state_attr('automation.nordpool_price_update', 'current') == 0 }}
    condition: []
    action: 
    - delay: 
        seconds: '{{ range(1,3600)|random|int }}'
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.nordpool_api

