timer:
  polestar:
    duration: 00:30:00
    restore: true
  polestar_inhibit:
    duration: 00:05:00
    restore: true

template:
  - sensor: 
      - name: rypse2_diff_dist
        unit_of_measurement: "km"
        state: >
          {% set saved = states('sensor.rypse2_saved_dist') %}
          {% set lat =  state_attr('device_tracker.polestar_dual', 'latitude') %}
          {% set lon = state_attr('device_tracker.polestar_dual', 'longitude') %}
          {% set dist = distance(lat, lon) %}
          {{ 0 if saved in ('unknown', 'Unavailable') else 
             (dist - saved|float)|abs|round(2) }}
  - binary_sensor: 
      - name: rypse2_charger_connected
        state: "{{ is_state('sensor.polestar_8958_charger_connection_status', 'Connected') }}"

  - trigger: 
    - platform: state
      entity_id:
        - sensor.polestar_8958_battery_charge_level
        - sensor.polestar_8958_charging_status
        - sensor.polestar_8958_charger_connection_status
        - sensor.polestar_8958_current_trip_meter_automatic
    sensor: 
      - name: rypse2_saved_dist
        unit_of_measurement: "km"
        state: >
          {% set lat =  state_attr('device_tracker.polestar_dual', 'latitude') %}
          {% set lon = state_attr('device_tracker.polestar_dual', 'longitude') %}
          {{ distance(lat, lon)|round(2) }}

automation:
  - alias: "Polestar timer integration"
    id: '1706544994327'
    trace:
      stored_traces: 15
    trigger: 
      - platform: state
        entity_id:
          - timer.polestar
        to: 'idle'
        id: timer
      - platform: state
        entity_id: device_tracker.polestar_dual
        id: tracker
      - platform: state
        entity_id: 
        - sensor.easee_home_63089_session_energy
        - sensor.easee_home_63089_status
        id: easee
      - platform: state
        entity_id: 
        - sensor.polestar_8958_battery_charge_level
        - sensor.polestar_8958_charger_connection_status
        - sensor.polestar_8958_charging_status
        - sensor.polestar_8958_current_trip_meter_automatic
        id: polestar
    action: 
      - choose: 
        - conditions:
          - condition: trigger
            id: polestar
          sequence:
            - service: timer.start
              target:
                entity_id: timer.polestar_inhibit
            - if: 
                - condition: state
                  entity_id: timer.polestar
                  state: 'active'
              then: 
                - service: timer.cancel
                  target:
                    entity_id: timer.polestar
        - conditions:
          - condition: state
            entity_id: 
              - timer.polestar_inhibit
              - timer.polestar
            state: 'idle'
          - condition: template
            value_template: "{{ trigger.entity_id != 'sensor.easee_home_63089_session_energy' or states('sensor.easee_home_63089_power')| float > 0 }}"
          - condition: or
            conditions: 
              - condition: trigger
                id: easee
              - condition: and
                conditions: 
                  - condition: trigger
                    id: tracker
                  - condition: numeric_state
                    entity_id: sensor.rypse2_diff_dist
                    above: 0.05
          sequence:
            - service: timer.start
              target:
                entity_id: timer.polestar
        - conditions:
          - condition: trigger
            id: timer
          - condition: state
            entity_id: 
            - timer.polestar_inhibit
            - timer.polestar
            state: 'idle'
          sequence:
            - service: notify.mobile_app_pixel_8
              data:
                message: Ser ut som vi har mistet kontakten med Polestar_api
                title: Polestar @ rypeveien
                data:
                  priority: high
    mode: queued
    max: 3
  - alias: "Polestar dual tracker"
    id: '1709718126123'
    trigger: 
      - platform: state
        entity_id:
          - device_tracker.polestar
          - device_tracker.rypse2
    action: 
      - service: device_tracker.see
        data:
          dev_id: polestar_dual
          location_name: "{{ trigger.to_state.state }}"
          gps: "[{{ trigger.to_state.attributes.latitude }}, {{trigger.to_state.attributes.longitude}}]"
          gps_accuracy: "{{ trigger.to_state.attributes.gps_accuracy }}"
