sensor:
  - platform: rest
    name: PostenDeliveryDays
    resource: https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/11?postCode=4878
    headers:
        x-requested-with: XMLHttpRequest
    scan_interval: 86400
    value_template: "{{ value_json.nextDeliveryDays|to_json }}"

template:
  binary_sensor: 
    - name: post_today
      state: >
        {% set delivery_days = states('sensor.postendeliverydays')|from_json %}
        {% set delivery_day = delivery_days[0].split(' ')[-2] %}
        {{ delivery_day|int == now().day }}

