automation:
  - id: '1673781385609'
    alias: 'Reload esp-vvmain if temp looks stuck'
    trigger: 
      - platform: template
        value_template: "{{ (now().timestamp() - states.sensor.vvtank_temp_ut.last_updated.timestamp())|int > 600 }}"
    action:
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: a4ace1a1ee9ba678904b7c6a271b988d

  - id: '1673781385619'
    alias: 'Reload esp-vvaux if temp looks stuck'
    trigger: 
      - platform: template
        value_template: "{{ (now().timestamp() - states.sensor.vvaux_temp.last_updated.timestamp())|int > 600 }}"
    action:
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: ecd58fc6843650fe416f6c1ea0bd1b30

  - id: '1671730925060'
    alias: 'Reload atom fryser whenever qp_kjellerstue freezes'
    trigger: 
      - platform: template
        value_template: "{{ states('sensor.qp_kjellerstue_temperature') in [ 'unavailable' ] }}"
    action:
      - delay:
          minutes: 5
      - if:
          - condition: template
            value_template: "{{ states('sensor.qp_kjellerstue_temperature') in [ 'unavailable' ] }}"
        then:
          - service: homeassistant.reload_config_entry
            data: {}
            target:
              device_id: 328534fc63b3984126f636379d634d05

  - id: '1671730925062'
    alias: 'Reload atom kontor whenever soverom_temperature freezes'
    trigger: 
      - platform: template
        value_template: "{{ states('sensor.soverom_temperature') in [ 'unavailable' ] }}"
    action:
      - delay:
          minutes: 5
      - if:
          - condition: template
            value_template: "{{ states('sensor.soverom_temperature') in [ 'unavailable' ] }}"
        then:
          - service: homeassistant.reload_config_entry
            data: {}
            target:
              device_id: dfe23fc0c4366e5de172a306aed5ea94
