timer:
  vacuum_timer:
    duration: "96:00:00"
    restore: true

automation:
  - id: '1644566778718'
    alias: Støvsug Mandag og Fredag når ingen er hjemme
    description: ''
    trigger:
    - platform: time
      at: '14:00'
      id: cleaningtime
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: "off"
      for: 
        minutes: 15
      id: home_alone
    - platform: state
      entity_id: timer.vacuum_timer
      to: 'idle'
    - platform: state
      entity_id: vacuum.martin
      from: 'cleaning'
      id: done_cleaning
    - platform: template
      value_template: >
        {{ states('binary_sensor.anyone_home') == 'on' }}
      id: noenkommerhjem
    condition: 
    - condition: state
      entity_id: input_boolean.fenrir_pa_besok
      state: "off"
    - condition: or
      conditions:
        - condition: trigger
          id: 
          - cleaningtime
          - done_cleaning
          - noenkommerhjem
        - condition: state
          entity_id: timer.vacuum_timer
          state: 'idle'
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: done_cleaning
        sequence:
        - if:
          - condition: numeric_state
            entity_id: sensor.martin_current_clean_area
            above: 35
          then: 
          - service: timer.cancel
            target:
              entity_id: timer.vacuum_timer
          - delay:
              minutes: 1
          - service: timer.start
            target:
              entity_id: timer.vacuum_timer
      - conditions:
        - condition: or
          conditions:
          - condition: trigger
            id: home_alone
          - condition: and
            conditions: 
            - condition: trigger
              id: cleaningtime
            - condition: state
              entity_id: binary_sensor.anyone_home
              state: 'off'
        - condition: or
          conditions:
          - condition: time
            after: '13:00'
            before: '14:15'
            weekday:
            - mon
            - fri
          - condition: state
            entity_id: timer.vacuum_timer
            state: 'idle'
        - condition: device
          device_id: 22bed80b6a2c686ba9af11178f87dc16
          domain: vacuum
          entity_id: vacuum.martin
          type: is_docked
        sequence:
        - device_id: 22bed80b6a2c686ba9af11178f87dc16
          domain: vacuum
          entity_id: vacuum.martin
          type: clean
      - conditions:
        - condition: trigger
          id: noenkommerhjem
        sequence:
        - choose:
          - conditions:
            - condition: device
              device_id: 22bed80b6a2c686ba9af11178f87dc16
              domain: vacuum
              entity_id: vacuum.martin
              type: is_cleaning
            sequence:
            - service: vacuum.pause
              data: {}
              target:
                device_id: 22bed80b6a2c686ba9af11178f87dc16
            - wait_template: "{{ states('vacuum.martin') == 'paused' }}"
              continue_on_timeout: true
              timeout: "60"
            - service: vacuum.return_to_base
              data: {}
              target:
                entity_id: vacuum.martin
          - conditions:
            - condition: state
              entity_id: vacuum.martin
              state: error
            sequence:
            - delay:
                hours: 0
                minutes: 2
                seconds: 0
                milliseconds: 0
            - service: media_player.volume_set
              data:
                volume_level: 0.3
              target:
                entity_id: media_player.stue
            - service: tts.google_translate_say
              data:
                entity_id: media_player.stue
                language: 'no'
                message: 'Hei, og velkommen hjem. Jeg har forsøkt å støvsuge, men har
                  satt meg fast. Kan du hjelpe meg ? '
            - delay:
                hours: 0
                minutes: 0
                seconds: 10
                milliseconds: 0
            - service: vacuum.locate
              data: {}
              target:
                entity_id: vacuum.martin
          default: []
      default: []
    mode: single
