template:
  - binary_sensor:
    - name: trainer_over_3_watt
      state: "{{ states('sensor.shellyrulle_power')|float(default=0) > 3 }}"
      delay_off:
        minutes: 15
  - trigger: 
      - platform: state
        entity_id: sensor.qp_kjellerstue_humidity
    sensor:
      - name: zwift saved humidity 
        unit_of_measurement: "%"
        state: >
          {% set to_state = trigger.to_state.state|float(default=50) %}
          {% set last = states('sensor.zwift_saved_humidity')|float(default=to_state) %}
          {% set active = states('binary_sensor.zwift_active') %}
          {% set zwiftlap = states('device_tracker.zwiftlap') %}
          {{ to_state if (zwiftlap != 'home' and active == 'off') else
             to_state if (zwiftlap == 'home' and active == 'on' and to_state > last) else
             to_state if (zwiftlap == 'home' and active == 'off' and to_state < last) else 
             last }}
    binary_sensor:
      - name: zwift_active
        state: >
          {% set active = states('binary_sensor.zwift_active') %}
          {% set zwift_hum = states('sensor.zwift_saved_humidity')|float %}
          {% set zwiftlap = states('device_tracker.zwiftlap') %}
          {% set trainer = states('switch.shellyrulle') %}
          {% set to_state = trigger.to_state.state|float %}
          {{ 'off' if 2 <= now().hour < 5 else 
             (to_state + 5) > zwift_hum if active == 'on' else 
             to_state > (zwift_hum + 2) if zwiftlap == 'home' else
             active }}

automation:
  - id: '1671655275820'
    alias: 'Set heatpump downstairs hvac mode when zwifting'
    trigger:
      - platform: state
        entity_id: binary_sensor.zwift_active
        id: active
      - platform: state
        entity_id: switch.shellyrulle
        to: "off"
        id: rulle
      - platform: numeric_state
        entity_id: sensor.shellyrulle_power
        below: 1.5
        for: 
          minutes: 45
        id: power
      - platform: state
        entity_id: light.kjellerstuetak
        to: "off"
        id: lights
    action:
      - if:
          - condition: trigger
            id: active
          - condition: state
            entity_id: binary_sensor.zwift_active
            state: "on"
        then:
          - if:
              - condition: state
                entity_id: climate.vp_gnede
                state: "heat"
            then:
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: dry
                target:
                  entity_id: climate.vpnede
              - service: climate.set_fan_mode
                data:
                  fan_mode: high
                target:
                  entity_id: climate.vpnede
          - service: switch.turn_on
            target:
              entity_id: switch.shellybikefan
        else:
          - if:
              - condition: state
                entity_id: climate.vp_gnede
                state: "heat"
              - condition: not
                conditions:
                - condition: state
                  entity_id: climate.vpnede
                  state: "heat"
            then:
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: heat
                target:
                  entity_id: climate.vpnede
              - service: climate.set_fan_mode
                data:
                  fan_mode: auto
                target:
                  entity_id: climate.vpnede
          - if:
              - condition: state
                entity_id: switch.shellyrulle
                state: "on"
            then:
              - service: switch.turn_off
                target:
                  entity_id: switch.shellyrulle
          - if:
              - condition: state
                entity_id: light.kjellerstuetak
                state: "on"
            then:
              - service: light.turn_off
                target:
                  entity_id: light.kjellerstuetak
          - if:
              - condition: state
                entity_id: switch.shellybikefan
                state: "on"
            then:
              - service: switch.turn_off
                target:
                  entity_id: switch.shellybikefan
